# site settings
title: Rickles Pickles Sidles NZ
subtitle: Te Araroa COVID Edition
description: Walking the length of NZ because what else are you going to do coming out of COVID?
baseurl: "/"
url: "https://www.ricklespicklessidles.nz"
author: Rick Chen

# social settings
instagram_url: https://www.instagram.com/_rickles_pickles_
facebook_url: https://www.facebook.com/rick.w.chen

collections:
  projects:
    output: true

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num/"
