# site settings
title: Rickles Pickles Sidles NZ
subtitle: Te Araroa COVID Edition
description: Walking the length of NZ because what else are you going to do coming out of COVID?
baseurl: "/"
url: "https://www.ricklespicklessidles.nz"
author: Rick Chen

# social settings
instagram_url: https://www.instagram.com/_rickles_pickles_
facebook_url: https://www.facebook.com/rick.w.chen

collections:
  projects:
    output: true

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num/"

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://staticman-ricklespicklessidles.herokuapp.com/v2/entry/rwjc/ricklespicklessidles/main/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
#reCaptcha:
#  siteKey: #6LfJU9UZAAAAANryPTR6Vc3-5DieL7Mngnx16jp6
#  secret: #bHt8lX9qX3Uxs33SvOqsU6Zu3Q7JnWjSoOYZmJZQwDpnyBcI1cErY8vHypOaJFTQw0hXi4FZ6k4TRFaWXLEKFKQ3UD9FVzOp6mLJKrIGOmd6UUZQubQVM1SOT8BGVtbQGjv9W1QKcR9ORuTIxDV5dADg9ldK19eq0bRANSCPj4S3hRC6EiiUA6DbsbuKhyGj+l40sCPA3eYr5IyPHRdVG734/ZoEwGfjgwo2wPRNna8DjmFirT2XhEcfQ4b/UTMZG0zDPAyfKpzCu+JqSWxkz9PPyk0C4QbZpGBOLzSF1NLWRzmissp6Scx+F+1f4aRWtI8eMqyyg3Vc+n3mLBrg96EXEIXnHo5CpvgLn5lTC3odTfcs7uZ+HTGY1m8f9ZEwxGd94sf2AVUXyrOdkwBGj3AxQqiTTsPCSvBHC5KAHftE9oSB7/6SpHwqmOLLeAA/wXcCAx/tj32W81S0oEJWt0D7ZhvuNQhMXzhyYpKxcSabG3ZUlxUi8XH9y6icTra1LKEBqOR7iJ2rn3RDtqEdPibNcFkD3FQeO4iJhRogIwwbkgqDQP1BUVjUfipwxrW9O/utRH+tydMlSNyvBREtM334jn7dl0ueaA0VVxTdGayyZ7nnunsVKPb8gMRdqhaoz8kFXUrZiqZvLp+QpwL/PieUKEKIBkzLoVSycfpFLoQ=
